# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o-9mCdV3F4Q5884CS5CWuDR6yX6eE1kt
"""

from setuptools import setup

setup(name='gym_spam',
      version='0.0.1',
      install_requires=['gym']
)